accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (login)

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
]

loja/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from loja.views import view_peca, CreateRoupas, ViewLoja, CreateImage, view_carrinho

urlpatterns = [

    url(r'^home/$', ViewLoja.as_view(), name='home'),
	url(r'^peca/(?P<pk>[-\w]+)/$', view_peca, name='view-peca'),
    url(r'^roupas/adicionar/$', CreateRoupas.as_view(), name='add-pecas'),
    url(r'^roupas/imagem/$', CreateImage.as_view(), name='add-imagem'),
    url(r'^carrinho/$', view_carrinho, name='view-carrinho'),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

palomitas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from palomitas import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^loja/', include('loja.urls', namespace='loja')),
    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

loja/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
	
#Method to create autoincrement id for boats.
def auto_increment_roupa_id():
	try:
		last_roupa = Roupas.objects.all().order_by('codigo').last().codigo
		roupa_id = int(last_roupa)+1
		roupa_id = str(roupa_id).zfill(4)
	except Exception as e:
		roupa_id = '0001'
	
	return roupa_id

ESCOLHA_GENERO = (
    ('Feminino', 'FEMININO'),
    ('Masculino','MASCULINO'),
    ('Unisex','UNISEX'),
)

class Roupas(models.Model):
	#owner = models.ForeignKey('cliente.Cliente', related_name='embarcacao')
	codigo = models.CharField(max_length=10, default=auto_increment_roupa_id)
	nome = models.CharField(max_length=70)
	tipo = models.CharField(max_length=70)
	genero = models.CharField(max_length=10, choices=ESCOLHA_GENERO)
	data_inclusao = models.DateTimeField(blank=True, null=True)
	tamanho = models.CharField(max_length=10, blank=True, null=True)
	valor_pago = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	valor_venda = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
	estoque = models.IntegerField(blank=True, null=True, default=1)
	imagem = models.FileField( upload_to='imagens_roupas', blank=True,)
	imagem1 = models.FileField( upload_to='imagens_roupas', blank=True,)
	imagem2 = models.FileField( upload_to='imagens_roupas', blank=True,)

	#methods
	def __str__(self):
		return self.nome

	#what todo after saving
	def save(self, *args, **kwargs):
		if (self.data_inclusao is None):
			self.data_inclusao = now()
		#captalize: deixa primeira letra maiuscula
		for field_name in ['nome', 'tipo' ]:
			val = getattr(self, field_name, False)
			if val:
				setattr(self, field_name, val.capitalize())
		#upper(): deixa todas as letras maiusculas.
		for field_name in [ 'tamanho' ]:
                        val = getattr(self, field_name, False)
                        if val:
                                setattr(self, field_name, val.upper())
		#important to call superclass method.
		#If you want the method to be called after is saved,
		#add yoiur lines after super method call
		super(Roupas, self).save(*args, **kwargs)


	def image_url(self):
		"""
		Returns the URL of the image associated with this Object.
		If an image hasn't been uploaded yet, it returns a stock image

		:returns: str -- the image url

		"""
		if self.imagem and hasattr(self.imagem, 'url'):
			return self.imagem.url           
		else:
			return '/static/images/sample.jpg'

	def image1_url(self):
		if self.imagem1 and hasattr(self.imagem1, 'url'):
			return self.imagem1.url
		else:
			return '/static/images/sample.jpg'

	def image2_url(self):
		if self.imagem2 and hasattr(self.imagem2, 'url'):
			return self.imagem2.url
		else:
			return '/static/images/sample.jpg'

vendas/models.py
from django.db import models

# Create your models here.

loja/forms.py
from django import forms
from .models import Roupas

class RoupasForm(forms.ModelForm):
	class Meta:
		model = Roupas
		fields = ['codigo', 'nome', 'tipo', 'genero', 'data_inclusao', 'tamanho', 'valor_pago', 
					'valor_venda', 'estoque','imagem', 'imagem1', 'imagem2'] 

class AdicionaProdutoCarrinho(forms.Forms):
    quantidade = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2',
        'value1:'1', 'class':'quantidade', 'maxlength':'5'}),
        error_messages={'invalid':'Favor colocar uma quantidade válida.'},
        min_value=1)
    codigo_produto = forms.CharField(widget=forms.HiddenInput())
    
    #override the default __init__ so we can set the request
    def __init__(self,request=None, *args, **kwargs):
        self.request = request
        super(AdicionaProdutoCarrinho, self).__init__(*args, **kwargs)
        
    # custom validation to check for cookies
    def clean(self):
        if not self.request.session.test_cookie_worked():
            raise forms.ValidationError("Cookies devem estar ativados.")
    return self.cleaned_data

accounts/views.py
from django.shortcuts import render

# Create your views here.

loja/views.py
from django.shortcuts import redirect, render, reverse, get_object_or_404
from loja.models import Roupas 
from loja.forms import RoupasForm
from django.views.generic import View

from django.views.generic.edit import CreateView

# Create your views here.

class ViewLoja(View):

    def get(self, request):
        """
        List the books that have reviews
        """
        roupas = Roupas.objects.all()
        query = request.GET.get("q")
        if query:
            roupas = roupas.filter(codigo__icontains=query)
        #roupas = Roupas.objects.exclude(date_reviewed__isnull=True).prefetch_related('authors')
        
    
        context = {
            'roupas': roupas,
        }
        return render(request, "loja.html", context)
        
    def post(self, request):
        form = RoupasForm(request.POST)
        roupas = Roupas.objects.all()
        
        if form.is_valid():
            cart = request.session.get('cart', {})
            cart[peca.codigo] = request.POST['quantidade']
            request.session['cart'] = cart
            return redirect('view_carrinho')
            
        context = {
            'form': form,
            'roupas': roupas,
        }
        
        return render(request, "loja.html", context)


def view_carrinho(request):
    cart = request.session.get('cart', {})
    # rest of the view
    context = {'cart': cart,}
    return render(request, "view-carrinho.html", context)

    
def view_peca(request, pk):
    """
    Review an individual book
    """
    peca = get_object_or_404(Roupas, pk=pk)
    
    if request.method == 'POST':
        # Process our form
        form = RoupasForm(request.POST, request.FILES, instance=peca)
        
        if form.is_valid():
            #book.is_favourite = form.cleaned_data['is_favourite']
            #book.review = form.cleaned_data['review']
            #book.reviewed_by = request.user
            peca.save()
            
            return redirect('loja:home')
        
    else:
        form = RoupasForm(instance=peca)
    
    context = {
        'peca': peca,
        'form': form,
    }
    
    return render(request, "edita-pecas.html", context)
    

class CreateRoupas(CreateView):
    model = Roupas
    fields = ['codigo', 'nome', 'tipo', 'genero', 'data_inclusao', 'tamanho', 'valor_pago', 
                    'valor_venda', 'estoque', 'imagem', 'imagem1', 'imagem2']
    template_name = "adiciona-pecas.html"
    
    def get_success_url(self):
        return reverse('loja:home')

class CreateImage(CreateView):
    model = Roupas
    fields = [ 'imagem' ]
    template_name = "adiciona-imagem.html"
    
    def get_success_url(self):
        return reverse('loja:home')

palomitas/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

vendas/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/login.html
{% extends 'login_base.html' %}

{% block content %}
<div class="container" align=center>
    <h1>Bem vindo.</h1>
    <p>Login</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
</div>
{% endblock %}

loja/templates/adiciona-imagem.html
{% extends "base.html" %}

{% block content %}

	<form method="post">
		{% csrf_token %}
 {{form.as_p}}

		<input type="submit" value="Adicionar peça">
</form>
{% endblock %}

loja/templates/adiciona-peca.html
{% extends "base.html" %}

{% block content %}
	<h1>Adiciona roupas</h1>

	<form method="post">
		{% csrf_token %}

		<label>{{ form.nome.label }}</label>
		{{ form.nome }}


		<p></p>

		<input type="submit" value="Add Book">
	</form>

{% endblock %}

loja/templates/adiciona-pecas.html
{% extends "base.html" %}

{% block content %}
	<h1>Adicionar novas peças</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% if form.non_field_errors %}
			<div class="non-field-errors">
				{% for error in form.non_field_errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}

		<p>
		<label>{{ form.codigo.label }}</label>
		{{ form.codigo }}
		{% if form.codigo.errors %}
			<div class="form-error">
				{% for error in form.codigo.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.nome.label }}</label>
		{{ form.nome }}

		{% if form.nome.errors %}
			<div class="form-error">
				{% for error in form.nome.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.tipo.label }}</label>
		{{ form.tipo }}
		{% if form.nome.errors %}
			<div class="form-error">
				{% for error in form.nome.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.genero.label }}</label>
		{{ form.genero }}
		{% if form.genero.errors %}
			<div class="form-error">
				{% for error in form.genero.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.tamanho.label }}</label>
		{{ form.tamanho }}
		{% if form.tamanho.errors %}
			<div class="form-error">
				{% for error in form.tamanho.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.valor_pago.label }}</label>
		{{ form.valor_pago }}
		{% if form.valor_pago.errors %}
			<div class="form-error">
				{% for error in form.valor_pago.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.valor_venda.label }}</label>
		{{ form.valor_venda }}
		{% if form.valor_venda.errors %}
			<div class="form-error">
				{% for error in form.valor_venda.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.estoque.label }}</label>
		{{ form.estoque }}
		{% if form.estoque.errors %}
			<div class="form-error">
				{% for error in form.estoque.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>

		<p><label for="imagem">Blabla:</label>
   		<input id="imagem" type="file" name="imagem" accept="image/*" /></p>
		{% if form.imagem.errors %}
			<div class="form-error">

				{% for error in form.imagem.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.imagem1.label }}</label>
		{{ form.imagem1 }}
		{% if form.imagem1.errors %}
			<div class="form-error">
				{% for error in form.imagem1.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.imagem2.label }}</label>
		{{ form.imagem2 }}
		{% if form.imagem2.errors %}
			<div class="form-error">
				{% for error in form.imagem2.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>

		<input type="submit" value="Adicionar peça">
	</form>
{% endblock %}

loja/templates/edita-pecas.html
{% extends "base.html" %}

{% block content %}
	<h1>{{ peca.nome }}</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% if form.non_field_errors %}
			<div class="non-field-errors">
				{% for error in form.non_field_errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}

		<p>
		<label>{{ form.codigo.label }}</label>
		{{ form.codigo }}
		{% if form.codigo.errors %}
			<div class="form-error">
				{% for error in form.codigo.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.nome.label }}</label>
		{{ form.nome }}

		{% if form.nome.errors %}
			<div class="form-error">
				{% for error in form.nome.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.tipo.label }}</label>
		{{ form.tipo }}
		{% if form.nome.errors %}
			<div class="form-error">
				{% for error in form.nome.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.genero.label }}</label>
		{{ form.genero }}
		{% if form.genero.errors %}
			<div class="form-error">
				{% for error in form.genero.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.tamanho.label }}</label>
		{{ form.tamanho }}
		{% if form.tamanho.errors %}
			<div class="form-error">
				{% for error in form.tamanho.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.valor_pago.label }}</label>
		{{ form.valor_pago }}
		{% if form.valor_pago.errors %}
			<div class="form-error">
				{% for error in form.valor_pago.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.valor_venda.label }}</label>
		{{ form.valor_venda }}
		{% if form.valor_venda.errors %}
			<div class="form-error">
				{% for error in form.valor_venda.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.estoque.label }}</label>
		{{ form.estoque }}
		{% if form.estoque.errors %}
			<div class="form-error">
				{% for error in form.estoque.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.imagem.label }}</label>
		{{ form.imagem }}
		{% if form.imagem.errors %}
			<div class="form-error">
				{% for error in form.imagem.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.imagem1.label }}</label>
		{{ form.imagem1 }}
		{% if form.imagem1.errors %}
			<div class="form-error">
				{% for error in form.imagem1.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
		<p>
		<label>{{ form.imagem2.label }}</label>
		{{ form.imagem2 }}
		{% if form.imagem2.errors %}
			<div class="form-error">
				{% for error in form.imagem2.errors %}
					<span>{{ error }}</span>
				{% endfor %}
			</div>
		{% endif %}
		</p>
			<img src="{{ peca.image_url }}" width="240">
			<img src="{{ peca.image1_url }}" width="240">
			<img src="{{ peca.image2_url }}" width="240">

			<p></p>

		<input type="submit" value="Salvar">
	</form>
{% endblock %}

loja/templates/home1.html
<!DOCTYPE html>
<html>
<title>W3.JS</title>

<body>
<main>
<script src="https://www.w3schools.com/lib/w3.js"></script>
<h2>Sort Tables</h2>

<p>Click the table headers to sort the  table accordingly:</p>

<table id="myTable">
  <tr>
    <th onclick="w3.sortHTML('#myTable', '.item', 'td:nth-child(1)')" style="cursor:pointer">Name</th>
    <th onclick="w3.sortHTML('#myTable', '.item', 'td:nth-child(2)')" style="cursor:pointer">Country</th>
  </tr>
  <tr class="item">
    <td>Berglunds snabbkop</td>
    <td>Sweden</td>
  </tr>
  <tr class="item">
    <td>North/South</td>
    <td>UK</td>
  </tr>
  <tr class="item">
    <td>Alfreds Futterkiste</td>
    <td>Germany</td>
  </tr>
  <tr class="item">
    <td>Koniglich Essen</td>
    <td>Germany</td>
  </tr>
  <tr class="item">
    <td>Magazzini Alimentari Riuniti</td>
    <td>Italy</td>
  </tr>
  <tr class="item">
    <td>Paris specialites</td>
    <td>France</td>
  </tr>
  <tr class="item">
    <td>Island Trading</td>
    <td>UK</td>
  </tr>
  <tr class="item">
    <td>Laughing Bacchus Winecellars</td>
    <td>Canada</td>
  </tr>
</table>
</main>
</body>
</html>

loja/templates/loja.html
{% extends "base.html" %}

{% block content %}
<script src="https://www.w3schools.com/lib/w3.js"></script>

	<h1>{{ roupas.count|title }} Peças</h1>
    <h2>{{ request.session.cart }}</h2>
	<form method="GET" action=''>
		<p><input type='text' name='q' placeholder="Pesquisar roupas"/>
		<input type='submit' value="Pesquisar" /></p>
	</form>
	<table id="pecasTable">
		<thead>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(1)')" style="cursor:pointer">Foto</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(2)')" style="cursor:pointer">Codigo</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(3)')" style="cursor:pointer">Nome</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(4)')" style="cursor:pointer">Tamanho</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(5)')" style="cursor:pointer">Genero</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(6)')" style="cursor:pointer">Tipo</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(7)')" style="cursor:pointer">Valor Compra</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(8)')" style="cursor:pointer">Valor Venda</th>
            <th onclick="w3.sortHTML('#pecasTable', '.item', 'td:nth-child(9)')" style="cursor:pointer">Estoque</th>
		</thead>
		<tbody>
			{% for peca in roupas %}
                
				<tr class="item">
					<td>
						{% ifequal peca.imagem None %}
							<img src="DEFAULT_IMAGE" />
						{% else %}
							<a href="{{ peca.image_url }}"><img src="{{ peca.image_url }}" width="240"></a>
						{% endifequal %}
					</td>
                    <td>
                        {{ peca.codigo }}
                    </td>
					<td>
						<a href="{% url 'loja:view-peca' peca.pk %}">
						{{ peca.nome }}
						</a>
					</td>
                    <td>
                        {{ peca.tamanho }}
                    </td>
                    <td>
                        {{ peca.genero}}
                    </td>
					<td>
						{{ peca.tipo }}
					</td>
                    <td>
                        {{ peca.valor_pago}}
                    </td>
					<td>
						{{ peca.valor_venda }}
					</td>
					<td>
						{{ peca.estoque}}
					</td>
					<td>
                        <form method="post" action='/loja/carrinho'>
                            {% csrf_token %}
                            <p><input type='text' name='quantidade' id='quantidade'/>
                            <input type='submit' value="Adicionar ao carrinho" /></p>
                        </form>
                    </td>
				</tr>
                
            {% endfor %}
		</tbody>
	</table>

{% endblock %}

palomitas/templates/base.html
{% load static %}
<!doctype html>
<html>
	<head>
		<title>Palomitas!</title>
		<meta charset="utf-8">
		<meta name="description"content="My great marina admin site">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700|Merriweather:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
	</head>
	<body>
		<div class="container">
			<header>
	
				
			</header>
			  <ul class="nav navbar-nav">
        	            <li><a href="{% url 'loja:home' %}">Home</a></li>
                	    <li><a href="{% url 'loja:add-pecas' %}">Adiciona peça</a></li>
   	                </ul>
		</div>
		<div class="container">
			
			<main>
				{% block content %}{% endblock %}
			</main>
			
			<footer>

			</footer>
		</div>
	</body>
</html>

palomitas/templates/login_base.html
{% load static %}
<!doctype html>
<html>
	<head>
		<title>Palomitas!</title>
		<meta charset="utf-8">
		<meta name="description"content="My great marina admin site">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700|Merriweather:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
	</head>
	<body>
		<div class="container">
			<header>
	
				
			</header>
			
			<main>
				{% block content %}{% endblock %}
			</main>
			
			<footer>

			</footer>
		</div>
	</body>
</html>